server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containerlogs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        # 필요한 컨테이너만 필터링
        filters:
          - name: label
            values: [logging=promtail]
    relabel_configs:
      # Docker 라벨에서 필요한 메타데이터 추출
      - source_labels: [__meta_docker_container_name]
        regex: "/(.*)"
        target_label: container
      - source_labels: [__meta_docker_container_log_stream]
        target_label: stream
      - source_labels: [__meta_docker_container_label_logging_jobname]
        target_label: job
      # 로그 타임스탬프 사용
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_docker_container_id
        target_label: __path__ 